/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPack;

import java.util.Timer;
import java.util.TimerTask;
import mainPack.MCP2515.CAN_Message;

/**
 *
 * @author pedronascimento
 */
public class mainFrame extends javax.swing.JFrame {

    private MCP2515 mcp2515 = null;
    Timer timer100ms;
    Timer timer1ms;
    
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    class task100ms extends TimerTask 
    {
        CAN_Message canMessage = mcp2515.new CAN_Message();;
        
        public void run() {
            canMessage.extended = true;
            canMessage.rtr = false;
            canMessage.data[0] = 0x01;
            canMessage.data[1] = 0x02;
            canMessage.data[2] = 0x03;
            canMessage.data[3] = 0x04;
            canMessage.data[4] = 0x05;
            canMessage.data[5] = 0x06;
            canMessage.data[6] = 0x07;
            canMessage.data[7] = 0x08;
            canMessage.dlc = 8;
            canMessage.id = 0x1234567B;
            mcp2515.send_message(canMessage);            
        }
    }
    
    class task1ms extends TimerTask 
    {
        CAN_Message canMessage = null;
        
        public void run() {
            
            canMessage = mcp2515.receive_message();
            if(canMessage != null){
                System.out.println("Message Received...");                
                System.out.println("Remote Frame: " + canMessage.rtr);
                System.out.println("Extended ID: " + canMessage.extended);
                System.out.println("ID: " + String.format("0x%08X", canMessage.id));
                System.out.println("DLC: " + canMessage.dlc);
                for(int i=0;i<canMessage.dlc;i++){
                   System.out.println(String.format("0x%02X ", canMessage.data[i]) + " "); 
                }
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CAN_Message canMessage = mcp2515.new CAN_Message();
                
        canMessage.extended = true;
        canMessage.rtr = false;
        canMessage.data[0] = 0x01;
        canMessage.data[1] = 0x02;
        canMessage.data[2] = 0x03;
        canMessage.data[3] = 0x04;
        canMessage.data[4] = 0x05;
        canMessage.data[5] = 0x06;
        canMessage.data[6] = 0x07;
        canMessage.data[7] = 0x08;
        canMessage.dlc = 8;
        canMessage.id = 0x1234567A;
        mcp2515.send_message(canMessage);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mcp2515 = new MCP2515();
        if(mcp2515.init()){
            System.out.println("CAN Opened");
        } else {
            System.out.println("CAN Not Opened");
        }
        
        timer100ms = new Timer();
        timer100ms.schedule(new task100ms(), 0, 100);
        
        //create a 1Khz task to read received messages
        timer1ms = new Timer();
        timer1ms.schedule(new task1ms(), 0, 1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
